/**
 * Copies ABIs out of Foundry's `out/` into `src/lib/abis/`.
 *
 * The frontend must never carry a hand-maintained copy of an ABI: the moment a
 * contract signature changes, a stale copy fails at runtime with an opaque
 * revert instead of at build time with a type error. Running this on every
 * `dev` and `build` keeps the two in lockstep.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const foundryOut = resolve(here, "../../out");
const abiDir = resolve(here, "../src/lib/abis");

/** artifact path in out/ -> exported const name */
const CONTRACTS = {
  "Insurance.sol/Insurance.json": "insuranceAbi",
  "Vault.sol/Vault.json": "vaultAbi",
  "FlightRegistry.sol/FlightRegistry.json": "flightRegistryAbi",
  "FlightAgent.sol/FlightAgent.json": "flightAgentAbi",
  "MockUSDC.sol/MockUSDC.json": "erc20Abi",
};

await mkdir(abiDir, { recursive: true });

const indexLines = [];

for (const [artifactPath, exportName] of Object.entries(CONTRACTS)) {
  const full = resolve(foundryOut, artifactPath);

  let raw;
  try {
    raw = await readFile(full, "utf8");
  } catch {
    console.error(
      `\n  Missing artifact: ${artifactPath}\n` +
        `  Run \`forge build\` in the repo root first.\n`,
    );
    process.exit(1);
  }

  const { abi } = JSON.parse(raw);
  if (!Array.isArray(abi)) {
    console.error(`  ${artifactPath} has no abi array`);
    process.exit(1);
  }

  const fileName = `${exportName}.ts`;
  const banner =
    `// Generated by scripts/export-abis.mjs from out/${artifactPath}\n` +
    `// Do not edit by hand — run \`npm run abis\` instead.\n\n`;

  await writeFile(
    resolve(abiDir, fileName),
    `${banner}export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`,
  );

  indexLines.push(`export { ${exportName} } from "./${exportName}";`);
  console.log(`  ${exportName.padEnd(20)} <- out/${artifactPath}`);
}

await writeFile(
  resolve(abiDir, "index.ts"),
  `// Generated by scripts/export-abis.mjs\n\n${indexLines.join("\n")}\n`,
);

console.log(`\n  Wrote ${indexLines.length} ABIs to src/lib/abis/\n`);
